// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/proto/payload.proto

package com.mcicu.protobufvsjson.protobuf;

public final class ProtoMessages {
  private ProtoMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BeaconsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo_namespace.Beacons)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .demo_namespace.Beacon beacons = 1;</code>
     */
    java.util.List<com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon> 
        getBeaconsList();
    /**
     * <code>repeated .demo_namespace.Beacon beacons = 1;</code>
     */
    com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon getBeacons(int index);
    /**
     * <code>repeated .demo_namespace.Beacon beacons = 1;</code>
     */
    int getBeaconsCount();
    /**
     * <code>repeated .demo_namespace.Beacon beacons = 1;</code>
     */
    java.util.List<? extends com.mcicu.protobufvsjson.protobuf.ProtoMessages.BeaconOrBuilder> 
        getBeaconsOrBuilderList();
    /**
     * <code>repeated .demo_namespace.Beacon beacons = 1;</code>
     */
    com.mcicu.protobufvsjson.protobuf.ProtoMessages.BeaconOrBuilder getBeaconsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code demo_namespace.Beacons}
   */
  public  static final class Beacons extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo_namespace.Beacons)
      BeaconsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Beacons.newBuilder() to construct.
    private Beacons(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Beacons() {
      beacons_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Beacons();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Beacons(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                beacons_ = new java.util.ArrayList<com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon>();
                mutable_bitField0_ |= 0x00000001;
              }
              beacons_.add(
                  input.readMessage(com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          beacons_ = java.util.Collections.unmodifiableList(beacons_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mcicu.protobufvsjson.protobuf.ProtoMessages.internal_static_demo_namespace_Beacons_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mcicu.protobufvsjson.protobuf.ProtoMessages.internal_static_demo_namespace_Beacons_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons.class, com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons.Builder.class);
    }

    public static final int BEACONS_FIELD_NUMBER = 1;
    private java.util.List<com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon> beacons_;
    /**
     * <code>repeated .demo_namespace.Beacon beacons = 1;</code>
     */
    public java.util.List<com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon> getBeaconsList() {
      return beacons_;
    }
    /**
     * <code>repeated .demo_namespace.Beacon beacons = 1;</code>
     */
    public java.util.List<? extends com.mcicu.protobufvsjson.protobuf.ProtoMessages.BeaconOrBuilder> 
        getBeaconsOrBuilderList() {
      return beacons_;
    }
    /**
     * <code>repeated .demo_namespace.Beacon beacons = 1;</code>
     */
    public int getBeaconsCount() {
      return beacons_.size();
    }
    /**
     * <code>repeated .demo_namespace.Beacon beacons = 1;</code>
     */
    public com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon getBeacons(int index) {
      return beacons_.get(index);
    }
    /**
     * <code>repeated .demo_namespace.Beacon beacons = 1;</code>
     */
    public com.mcicu.protobufvsjson.protobuf.ProtoMessages.BeaconOrBuilder getBeaconsOrBuilder(
        int index) {
      return beacons_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < beacons_.size(); i++) {
        output.writeMessage(1, beacons_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < beacons_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, beacons_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons)) {
        return super.equals(obj);
      }
      com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons other = (com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons) obj;

      if (!getBeaconsList()
          .equals(other.getBeaconsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getBeaconsCount() > 0) {
        hash = (37 * hash) + BEACONS_FIELD_NUMBER;
        hash = (53 * hash) + getBeaconsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo_namespace.Beacons}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo_namespace.Beacons)
        com.mcicu.protobufvsjson.protobuf.ProtoMessages.BeaconsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mcicu.protobufvsjson.protobuf.ProtoMessages.internal_static_demo_namespace_Beacons_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mcicu.protobufvsjson.protobuf.ProtoMessages.internal_static_demo_namespace_Beacons_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons.class, com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons.Builder.class);
      }

      // Construct using com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBeaconsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (beaconsBuilder_ == null) {
          beacons_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          beaconsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mcicu.protobufvsjson.protobuf.ProtoMessages.internal_static_demo_namespace_Beacons_descriptor;
      }

      @java.lang.Override
      public com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons getDefaultInstanceForType() {
        return com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons.getDefaultInstance();
      }

      @java.lang.Override
      public com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons build() {
        com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons buildPartial() {
        com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons result = new com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons(this);
        int from_bitField0_ = bitField0_;
        if (beaconsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            beacons_ = java.util.Collections.unmodifiableList(beacons_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.beacons_ = beacons_;
        } else {
          result.beacons_ = beaconsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons) {
          return mergeFrom((com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons other) {
        if (other == com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons.getDefaultInstance()) return this;
        if (beaconsBuilder_ == null) {
          if (!other.beacons_.isEmpty()) {
            if (beacons_.isEmpty()) {
              beacons_ = other.beacons_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBeaconsIsMutable();
              beacons_.addAll(other.beacons_);
            }
            onChanged();
          }
        } else {
          if (!other.beacons_.isEmpty()) {
            if (beaconsBuilder_.isEmpty()) {
              beaconsBuilder_.dispose();
              beaconsBuilder_ = null;
              beacons_ = other.beacons_;
              bitField0_ = (bitField0_ & ~0x00000001);
              beaconsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBeaconsFieldBuilder() : null;
            } else {
              beaconsBuilder_.addAllMessages(other.beacons_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon> beacons_ =
        java.util.Collections.emptyList();
      private void ensureBeaconsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          beacons_ = new java.util.ArrayList<com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon>(beacons_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon, com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon.Builder, com.mcicu.protobufvsjson.protobuf.ProtoMessages.BeaconOrBuilder> beaconsBuilder_;

      /**
       * <code>repeated .demo_namespace.Beacon beacons = 1;</code>
       */
      public java.util.List<com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon> getBeaconsList() {
        if (beaconsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(beacons_);
        } else {
          return beaconsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .demo_namespace.Beacon beacons = 1;</code>
       */
      public int getBeaconsCount() {
        if (beaconsBuilder_ == null) {
          return beacons_.size();
        } else {
          return beaconsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .demo_namespace.Beacon beacons = 1;</code>
       */
      public com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon getBeacons(int index) {
        if (beaconsBuilder_ == null) {
          return beacons_.get(index);
        } else {
          return beaconsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .demo_namespace.Beacon beacons = 1;</code>
       */
      public Builder setBeacons(
          int index, com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon value) {
        if (beaconsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBeaconsIsMutable();
          beacons_.set(index, value);
          onChanged();
        } else {
          beaconsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .demo_namespace.Beacon beacons = 1;</code>
       */
      public Builder setBeacons(
          int index, com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon.Builder builderForValue) {
        if (beaconsBuilder_ == null) {
          ensureBeaconsIsMutable();
          beacons_.set(index, builderForValue.build());
          onChanged();
        } else {
          beaconsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .demo_namespace.Beacon beacons = 1;</code>
       */
      public Builder addBeacons(com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon value) {
        if (beaconsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBeaconsIsMutable();
          beacons_.add(value);
          onChanged();
        } else {
          beaconsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .demo_namespace.Beacon beacons = 1;</code>
       */
      public Builder addBeacons(
          int index, com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon value) {
        if (beaconsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBeaconsIsMutable();
          beacons_.add(index, value);
          onChanged();
        } else {
          beaconsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .demo_namespace.Beacon beacons = 1;</code>
       */
      public Builder addBeacons(
          com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon.Builder builderForValue) {
        if (beaconsBuilder_ == null) {
          ensureBeaconsIsMutable();
          beacons_.add(builderForValue.build());
          onChanged();
        } else {
          beaconsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .demo_namespace.Beacon beacons = 1;</code>
       */
      public Builder addBeacons(
          int index, com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon.Builder builderForValue) {
        if (beaconsBuilder_ == null) {
          ensureBeaconsIsMutable();
          beacons_.add(index, builderForValue.build());
          onChanged();
        } else {
          beaconsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .demo_namespace.Beacon beacons = 1;</code>
       */
      public Builder addAllBeacons(
          java.lang.Iterable<? extends com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon> values) {
        if (beaconsBuilder_ == null) {
          ensureBeaconsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, beacons_);
          onChanged();
        } else {
          beaconsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .demo_namespace.Beacon beacons = 1;</code>
       */
      public Builder clearBeacons() {
        if (beaconsBuilder_ == null) {
          beacons_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          beaconsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .demo_namespace.Beacon beacons = 1;</code>
       */
      public Builder removeBeacons(int index) {
        if (beaconsBuilder_ == null) {
          ensureBeaconsIsMutable();
          beacons_.remove(index);
          onChanged();
        } else {
          beaconsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .demo_namespace.Beacon beacons = 1;</code>
       */
      public com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon.Builder getBeaconsBuilder(
          int index) {
        return getBeaconsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .demo_namespace.Beacon beacons = 1;</code>
       */
      public com.mcicu.protobufvsjson.protobuf.ProtoMessages.BeaconOrBuilder getBeaconsOrBuilder(
          int index) {
        if (beaconsBuilder_ == null) {
          return beacons_.get(index);  } else {
          return beaconsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .demo_namespace.Beacon beacons = 1;</code>
       */
      public java.util.List<? extends com.mcicu.protobufvsjson.protobuf.ProtoMessages.BeaconOrBuilder> 
           getBeaconsOrBuilderList() {
        if (beaconsBuilder_ != null) {
          return beaconsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(beacons_);
        }
      }
      /**
       * <code>repeated .demo_namespace.Beacon beacons = 1;</code>
       */
      public com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon.Builder addBeaconsBuilder() {
        return getBeaconsFieldBuilder().addBuilder(
            com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon.getDefaultInstance());
      }
      /**
       * <code>repeated .demo_namespace.Beacon beacons = 1;</code>
       */
      public com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon.Builder addBeaconsBuilder(
          int index) {
        return getBeaconsFieldBuilder().addBuilder(
            index, com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon.getDefaultInstance());
      }
      /**
       * <code>repeated .demo_namespace.Beacon beacons = 1;</code>
       */
      public java.util.List<com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon.Builder> 
           getBeaconsBuilderList() {
        return getBeaconsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon, com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon.Builder, com.mcicu.protobufvsjson.protobuf.ProtoMessages.BeaconOrBuilder> 
          getBeaconsFieldBuilder() {
        if (beaconsBuilder_ == null) {
          beaconsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon, com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon.Builder, com.mcicu.protobufvsjson.protobuf.ProtoMessages.BeaconOrBuilder>(
                  beacons_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          beacons_ = null;
        }
        return beaconsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo_namespace.Beacons)
    }

    // @@protoc_insertion_point(class_scope:demo_namespace.Beacons)
    private static final com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons();
    }

    public static com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Beacons>
        PARSER = new com.google.protobuf.AbstractParser<Beacons>() {
      @java.lang.Override
      public Beacons parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Beacons(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Beacons> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Beacons> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacons getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BeaconOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo_namespace.Beacon)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>float latitude = 2;</code>
     * @return The latitude.
     */
    float getLatitude();

    /**
     * <code>float longitude = 3;</code>
     * @return The longitude.
     */
    float getLongitude();
  }
  /**
   * Protobuf type {@code demo_namespace.Beacon}
   */
  public  static final class Beacon extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo_namespace.Beacon)
      BeaconOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Beacon.newBuilder() to construct.
    private Beacon(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Beacon() {
      id_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Beacon();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Beacon(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 21: {

              latitude_ = input.readFloat();
              break;
            }
            case 29: {

              longitude_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mcicu.protobufvsjson.protobuf.ProtoMessages.internal_static_demo_namespace_Beacon_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mcicu.protobufvsjson.protobuf.ProtoMessages.internal_static_demo_namespace_Beacon_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon.class, com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LATITUDE_FIELD_NUMBER = 2;
    private float latitude_;
    /**
     * <code>float latitude = 2;</code>
     * @return The latitude.
     */
    public float getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 3;
    private float longitude_;
    /**
     * <code>float longitude = 3;</code>
     * @return The longitude.
     */
    public float getLongitude() {
      return longitude_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (latitude_ != 0F) {
        output.writeFloat(2, latitude_);
      }
      if (longitude_ != 0F) {
        output.writeFloat(3, longitude_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (latitude_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, latitude_);
      }
      if (longitude_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, longitude_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon)) {
        return super.equals(obj);
      }
      com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon other = (com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (java.lang.Float.floatToIntBits(getLatitude())
          != java.lang.Float.floatToIntBits(
              other.getLatitude())) return false;
      if (java.lang.Float.floatToIntBits(getLongitude())
          != java.lang.Float.floatToIntBits(
              other.getLongitude())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getLatitude());
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getLongitude());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo_namespace.Beacon}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo_namespace.Beacon)
        com.mcicu.protobufvsjson.protobuf.ProtoMessages.BeaconOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mcicu.protobufvsjson.protobuf.ProtoMessages.internal_static_demo_namespace_Beacon_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mcicu.protobufvsjson.protobuf.ProtoMessages.internal_static_demo_namespace_Beacon_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon.class, com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon.Builder.class);
      }

      // Construct using com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        latitude_ = 0F;

        longitude_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mcicu.protobufvsjson.protobuf.ProtoMessages.internal_static_demo_namespace_Beacon_descriptor;
      }

      @java.lang.Override
      public com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon getDefaultInstanceForType() {
        return com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon.getDefaultInstance();
      }

      @java.lang.Override
      public com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon build() {
        com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon buildPartial() {
        com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon result = new com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon(this);
        result.id_ = id_;
        result.latitude_ = latitude_;
        result.longitude_ = longitude_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon) {
          return mergeFrom((com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon other) {
        if (other == com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.getLatitude() != 0F) {
          setLatitude(other.getLatitude());
        }
        if (other.getLongitude() != 0F) {
          setLongitude(other.getLongitude());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private float latitude_ ;
      /**
       * <code>float latitude = 2;</code>
       * @return The latitude.
       */
      public float getLatitude() {
        return latitude_;
      }
      /**
       * <code>float latitude = 2;</code>
       * @param value The latitude to set.
       * @return This builder for chaining.
       */
      public Builder setLatitude(float value) {
        
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float latitude = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatitude() {
        
        latitude_ = 0F;
        onChanged();
        return this;
      }

      private float longitude_ ;
      /**
       * <code>float longitude = 3;</code>
       * @return The longitude.
       */
      public float getLongitude() {
        return longitude_;
      }
      /**
       * <code>float longitude = 3;</code>
       * @param value The longitude to set.
       * @return This builder for chaining.
       */
      public Builder setLongitude(float value) {
        
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float longitude = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitude() {
        
        longitude_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo_namespace.Beacon)
    }

    // @@protoc_insertion_point(class_scope:demo_namespace.Beacon)
    private static final com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon();
    }

    public static com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Beacon>
        PARSER = new com.google.protobuf.AbstractParser<Beacon>() {
      @java.lang.Override
      public Beacon parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Beacon(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Beacon> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Beacon> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.mcicu.protobufvsjson.protobuf.ProtoMessages.Beacon getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_namespace_Beacons_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_namespace_Beacons_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_namespace_Beacon_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_namespace_Beacon_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035resources/proto/payload.proto\022\016demo_na" +
      "mespace\"2\n\007Beacons\022\'\n\007beacons\030\001 \003(\0132\026.de" +
      "mo_namespace.Beacon\"9\n\006Beacon\022\n\n\002id\030\001 \001(" +
      "\t\022\020\n\010latitude\030\002 \001(\002\022\021\n\tlongitude\030\003 \001(\002B2" +
      "\n!com.mcicu.protobufvsjson.protobufB\rPro" +
      "toMessagesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_demo_namespace_Beacons_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_namespace_Beacons_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_namespace_Beacons_descriptor,
        new java.lang.String[] { "Beacons", });
    internal_static_demo_namespace_Beacon_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_demo_namespace_Beacon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_namespace_Beacon_descriptor,
        new java.lang.String[] { "Id", "Latitude", "Longitude", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
