// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/proto/payload.proto

package com.mcicu.protobufvsjson.proto_pojos;

public final class Payload {
  private Payload() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BeaconOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo_namespace.Beacon)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>int32 latitude = 2;</code>
     * @return The latitude.
     */
    int getLatitude();

    /**
     * <code>int32 longitude = 3;</code>
     * @return The longitude.
     */
    int getLongitude();
  }
  /**
   * Protobuf type {@code demo_namespace.Beacon}
   */
  public  static final class Beacon extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo_namespace.Beacon)
      BeaconOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Beacon.newBuilder() to construct.
    private Beacon(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Beacon() {
      id_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Beacon();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Beacon(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 16: {

              latitude_ = input.readInt32();
              break;
            }
            case 24: {

              longitude_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mcicu.protobufvsjson.proto_pojos.Payload.internal_static_demo_namespace_Beacon_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mcicu.protobufvsjson.proto_pojos.Payload.internal_static_demo_namespace_Beacon_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon.class, com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LATITUDE_FIELD_NUMBER = 2;
    private int latitude_;
    /**
     * <code>int32 latitude = 2;</code>
     * @return The latitude.
     */
    public int getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 3;
    private int longitude_;
    /**
     * <code>int32 longitude = 3;</code>
     * @return The longitude.
     */
    public int getLongitude() {
      return longitude_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (latitude_ != 0) {
        output.writeInt32(2, latitude_);
      }
      if (longitude_ != 0) {
        output.writeInt32(3, longitude_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (latitude_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, latitude_);
      }
      if (longitude_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, longitude_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon)) {
        return super.equals(obj);
      }
      com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon other = (com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (getLatitude()
          != other.getLatitude()) return false;
      if (getLongitude()
          != other.getLongitude()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + getLatitude();
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + getLongitude();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo_namespace.Beacon}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo_namespace.Beacon)
        com.mcicu.protobufvsjson.proto_pojos.Payload.BeaconOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mcicu.protobufvsjson.proto_pojos.Payload.internal_static_demo_namespace_Beacon_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mcicu.protobufvsjson.proto_pojos.Payload.internal_static_demo_namespace_Beacon_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon.class, com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon.Builder.class);
      }

      // Construct using com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        latitude_ = 0;

        longitude_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mcicu.protobufvsjson.proto_pojos.Payload.internal_static_demo_namespace_Beacon_descriptor;
      }

      @java.lang.Override
      public com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon getDefaultInstanceForType() {
        return com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon.getDefaultInstance();
      }

      @java.lang.Override
      public com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon build() {
        com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon buildPartial() {
        com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon result = new com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon(this);
        result.id_ = id_;
        result.latitude_ = latitude_;
        result.longitude_ = longitude_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon) {
          return mergeFrom((com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon other) {
        if (other == com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.getLatitude() != 0) {
          setLatitude(other.getLatitude());
        }
        if (other.getLongitude() != 0) {
          setLongitude(other.getLongitude());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private int latitude_ ;
      /**
       * <code>int32 latitude = 2;</code>
       * @return The latitude.
       */
      public int getLatitude() {
        return latitude_;
      }
      /**
       * <code>int32 latitude = 2;</code>
       * @param value The latitude to set.
       * @return This builder for chaining.
       */
      public Builder setLatitude(int value) {
        
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 latitude = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatitude() {
        
        latitude_ = 0;
        onChanged();
        return this;
      }

      private int longitude_ ;
      /**
       * <code>int32 longitude = 3;</code>
       * @return The longitude.
       */
      public int getLongitude() {
        return longitude_;
      }
      /**
       * <code>int32 longitude = 3;</code>
       * @param value The longitude to set.
       * @return This builder for chaining.
       */
      public Builder setLongitude(int value) {
        
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 longitude = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitude() {
        
        longitude_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo_namespace.Beacon)
    }

    // @@protoc_insertion_point(class_scope:demo_namespace.Beacon)
    private static final com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon();
    }

    public static com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Beacon>
        PARSER = new com.google.protobuf.AbstractParser<Beacon>() {
      @java.lang.Override
      public Beacon parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Beacon(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Beacon> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Beacon> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.mcicu.protobufvsjson.proto_pojos.Payload.Beacon getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_namespace_Beacon_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_namespace_Beacon_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035resources/proto/payload.proto\022\016demo_na" +
      "mespace\"9\n\006Beacon\022\n\n\002id\030\001 \001(\t\022\020\n\010latitud" +
      "e\030\002 \001(\005\022\021\n\tlongitude\030\003 \001(\005B&\n$com.mcicu." +
      "protobufvsjson.proto_pojosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_demo_namespace_Beacon_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_namespace_Beacon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_namespace_Beacon_descriptor,
        new java.lang.String[] { "Id", "Latitude", "Longitude", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
